// <auto-generated />
namespace CarRentalApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class migration_one : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration_one));
        
        string IMigrationMetadata.Id
        {
            get { return "202408081057347_migration_one"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
